# Generated by Django 5.2 on 2025-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightlog',
            old_name='remarks',
            new_name='Additional_note',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='tail_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightcategory',
            name='mission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Co_Pilot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Day_night',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Instrument_Flu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Landing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Pilot_in_comm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='Take_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightcategory',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightcategory',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
