# Generated by Django 5.2 on 2025-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0002_rename_remarks_flightlog_additional_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
