# Generated by Django 5.2 on 2025-04-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0003_flightlog_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='type',
            new_name='typee',
        ),
    ]
