# Generated by Django 5.2 on 2025-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0004_rename_type_aircraft_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='typee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
